2018-06-10 12:24:28,298 ERROR: Exception on /gamepage [POST] [in /home/scott/.local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/scott/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/scott/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/scott/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/scott/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/scott/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/scott/.local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/scott/python_env/dictionary_game_2018/microblog/app/routes.py", line 195, in gamepage
    r['player_name'] + ': ' + str(r['player_score']))
TypeError: 'int' object has no attribute '__getitem__'
2018-06-10 12:26:06,043 INFO: Microblog startup [in /home/scott/python_env/dictionary_game_2018/microblog/app/__init__.py:47]
2018-06-10 12:29:15,652 INFO: Microblog startup [in /home/scott/python_env/dictionary_game_2018/microblog/app/__init__.py:47]
